name: Build disk images
permissions: write-all

env:
  FALLBACK_BRANCH: "44"
  BUILD_TAG: ${{ github.ref_name || env.FALLBACK_BRANCH }}

on:
  schedule:
    - cron: "0 4 * * *" # every day at 4am UTC
  workflow_dispatch:
  workflow_run:
    workflows: ["Build bootc images"]
    types:
      - completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build-iso:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        variant:
          - name: gnome
            image: ghcr.io/ultramarine-linux/gnome-bootc:${{ env.BUILD_TAG }}
          - name: plasma
            image: ghcr.io/ultramarine-linux/plasma-bootc:${{ env.BUILD_TAG }}
          - name: xfce
            image: ghcr.io/ultramarine-linux/xfce-bootc:${{ env.BUILD_TAG }}
          - name: budgie
            image: ghcr.io/ultramarine-linux/budgie-bootc:${{ env.BUILD_TAG }}
    name: Build disk images
    runs-on: ${{ contains(matrix.arch, 'aarch64') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}

    container:
      image: ${{ matrix.variant.image }}
      options: --privileged --security-opt seccomp=unconfined -v /usr:/hostusr -v /:/hostfs -v /dev:/dev

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Clean up space before build
        run: |
          df -h
          # Wipe stuff in our host /usr to make some space

          # We don't need the android SDK
          rm -rf /hostusr/local/lib/android
          # We're a Rust shop, not a Haskell shop
          rm -rf /hostusr/local/.ghcup
          rm -rf /hostfs/opt/ghc
          # We don't even use .NET
          rm -rf /hostusr/share/dotnet
          # We don't need CodeQL in this action
          rm -rf /hostfs/opt/hostedtoolcache/CodeQL


          echo "After cleanup:"
          df -h
      - name: Build disk image
        run: |
          set -euxo pipefail
          IMAGE_TAG=${{ matrix.variant.image }}
          IMAGE_SIZE=24G
          FILESYSTEM=btrfs

          # Create disk image
          fallocate -l $IMAGE_SIZE disk.raw
          # Build disk image using bootc install to-disk

          bootc install to-disk $PWD/disk.raw \
            --source-imgref docker://${IMAGE_TAG} \
            --via-loopback \
            --generic-image \
            --filesystem $FILESYSTEM

          xz -9 -T0 disk.raw



      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: iso-artifact-${{ github.run_id }}-${{ matrix.variant.name }}-${{ matrix.arch }}
          path: ./*.xz
          compression-level: 0
